# Generated by Django 2.0.4 on 2018-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20180424_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lable',
            field=models.CharField(default='帖子标签', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='帖子作者', max_length=32),
        ),
    ]
