# Generated by Django 2.0.4 on 2018-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20180426_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='输入评论', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='帖子概要', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='view_account',
            field=models.IntegerField(default=0),
        ),
    ]
