# Generated by Django 2.0.4 on 2018-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_bbs_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='signature',
            field=models.CharField(default='这个人太懒了，什么也没有留下...', max_length=128),
        ),
    ]
