# Generated by Django 2.0.4 on 2018-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20180427_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_time',
            field=models.DateTimeField(null=True),
        ),
    ]
