# Generated by Django 2.0.4 on 2018-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_auto_20180427_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='up_time',
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='帖子作者', max_length=32),
        ),
    ]
