# Generated by Django 2.0.4 on 2018-05-02 08:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('bbs', '0016_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lable',
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
