# Generated by Django 2.0.4 on 2018-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0017_auto_20180502_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(default='输入评论', max_length=100),
        ),
    ]
